version: '3.3'
services:
   # ElasticSearch service
   elasticsearch:
      container_name: elasticsearch
      network_mode: host
      image: 'elasticsearch:7.9.3'
      environment:
         - discovery.type=single-node
   # Kibana service
   kibana:
      container_name: kibana
      network_mode: host
      image: 'kibana:7.9.3'
      environment:
         - 'ELASTICSEARCH_HOSTS=http://localhost:9200'
   logstash:
      container_name: logstash
      network_mode: host
      image: 'logstash:7.9.3'
      volumes:
         - './logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf'
         - './data/:/usr/share/data/'
      environment:
         - 'PIPELINE_WORKERS=1'

